[package]
name = "stratum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettyplease = "0.2.4"
proc-macro2 = "1.0.56"
quote = "1.0.26"
rug = "1.19.2"
syn = "2.0.14"
