//! Facilities for pest error reporting.

use crate::grammar::Rule;

/// Stringify a rule in a human-friendly format.
pub fn pretty_print_rule(rule: &Rule) -> &'static str {
    match rule {
        Rule::EOI => "end of input",
        Rule::program => "a program",
        Rule::fun => "a function",
        Rule::params => "function parameters",
        Rule::struct_def => "a `struct` definition",
        Rule::trait_def => "a `trait` definition",
        Rule::enum_def => "an `enum` definition",
        Rule::variant_def => "an `enum` variant",
        Rule::method_sig => "a method signature",
        Rule::block => "a block",
        Rule::stmt => "a statement",
        Rule::return_stmt => "`return expr;`",
        Rule::break_stmt => "`break;`",
        Rule::continue_stmt => "`continue;`",
        Rule::while_loop => "a while loop",
        Rule::for_loop => "a for loop",
        Rule::loop_loop => "some `loop { ... }`",
        Rule::assign => "an assignment",
        Rule::declare => "`var x = /**/`",
        Rule::vardef => "`x : type`",
        Rule::expr => "an expression",
        Rule::subexpr => "`( expr )`",
        Rule::tuple => "a tuple `(x, y, z, ...)`",
        Rule::binop => " a binary operator",
        Rule::with_postfix => "an expression",
        Rule::primitive => "an expression (without postfix `()`, `[]` `.`, or `..`)",
        Rule::field_postfix => "`.field`",
        Rule::tuple_idx => "a tuple index (0, 1, 2, etc.)",
        Rule::index_postfix => "`[index]`",
        Rule::call_postfix => "`(arg1, arg2, ...)`",
        Rule::range_postfix => "`..expr`",
        Rule::struct_instance => "`MyStruct { ... }`",
        Rule::unit => "`()`",
        Rule::integer_wrapper => "an integer",
        Rule::integer => "an integer",
        Rule::integer_suffix => "an integer suffix (e.g. `u`)",
        Rule::boolean => "a boolean",
        Rule::string => "a string",
        Rule::param => "a function parameter",
        Rule::ty => "a type",
        Rule::arg => "an argument to a function",
        Rule::std_arg => "some expression",
        Rule::in_place_arg => "an in-place argument `@place`",
        Rule::binding_arg => "a binding argument `expr@place`",
        Rule::self_param => "a `self` parameter",
        Rule::array_ty => "an array type",
        Rule::tuple_ty => "a tuple type",
        Rule::bool_ty => "the `bool` type",
        Rule::str_ty => "the `str` type",
        Rule::int_ty => "the `int` type",
        Rule::keyword => "some reserved keyword",
        Rule::infix => "an infix operator",
        Rule::prefix => "a prefix operator",
        Rule::ident => "an identifier (`a-Z[a-Z | 0-9]*` except reserved keywords)",
        Rule::namespaced => "`a::b::c`",
        Rule::if_then => "`if cond {}`",
        Rule::match_expr => "a `match`",
        Rule::array => "`[a,b,c,...]`",
        Rule::iter_ty => "`type..`",
        Rule::non_iter_ty => "a type (except an iterator type)",
        Rule::WHITESPACE => "a whitespace",
        Rule::COMMENT => "a comment",
        // Tokens
        Rule::sc => "`;`",
        Rule::lcb => "`{`",
        Rule::rcb => "`}`",
        Rule::eq => "`=`",
        Rule::add => "`+`",
        Rule::sub => "`-`",
        Rule::mul => "`*`",
        Rule::div => "`/`",
        Rule::rem => "`%`",
        Rule::pow => "`^`",
        Rule::le => "`<=`",
        Rule::lt => "`<`",
        Rule::ge => "`>=`",
        Rule::gt => "`>`",
        Rule::eqq => "`==`",
        Rule::neq => "`!=`",
        Rule::and => "`&&`",
        Rule::or => "`||`",
        Rule::not_in => "`not in`",
        Rule::bang => "`!`",
        Rule::not => "`not`",
        Rule::as_mut => "`@`",
        Rule::cln => "`:`",
        Rule::cma => "`,`",
        Rule::rg => "`..`",
        Rule::arw => "`->`",
        Rule::farw => "`=>`",
        Rule::pipe => "`|`",
        Rule::lp => "`(`",
        Rule::rp => "`)`",
        Rule::lb => "`[`",
        Rule::rb => "`]`",
        Rule::dt => "`.`",
        Rule::swap_kw => "`<->`",
        Rule::swap => "a swap operation",
        Rule::clncln => "`::`",
        Rule::while_kw => "`while`",
        Rule::loop_kw => "`loop`",
        Rule::for_kw => "`for`",
        Rule::in_kw => "`in`",
        Rule::if_kw => "`if`",
        Rule::else_kw => "`else`",
        Rule::var_kw => "`var`",
        Rule::fn_kw => "`fn`",
        Rule::struct_kw => "`struct`",
        Rule::trait_kw => "`trait`",
        Rule::self_kw => "`self`",
        Rule::enum_kw => "`enum`",
        Rule::match_kw => "`match`",
        Rule::break_kw => "`break`",
        Rule::return_kw => "`return`",
        Rule::continue_kw => "`continue`",
        Rule::match_block => "`{ i1 => e1 | ... | in => en }",
        Rule::matched_expr => "an expression (except a struct instance)",
        Rule::matched_primitive | Rule::primitive_wo_struct => {
            "an expression (without postfix `()`, `[]` `.`, or `..`) except a structure instance"
        }
    }
}
