[package]
name = "vache-tests-proc"
authors=["Jonathan ARNOULT <jonathan.arnoult@polytechnique.edu>"]
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.27"
syn = "2.0.16"
glob = "0.3.1"
