name: Rust Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --all
      - name: Run tests
        run: cargo test --verbose --all
      - name: Format Check
        run: cargo fmt --all --verbose --check
      - name: Clippy Check
        run: cargo clippy --all --verbose
      - name: Generate Docs
        if: github.ref == 'refs/heads/master'
        run: |
          rm -rf ./docs
          cargo doc --no-deps
          echo "<meta http-equiv=\"refresh\" content=\"0; url=vache\">" > target/doc/index.html
          cp -r target/doc ./docs
